---
- name: Create user
  user:
    name: "{{ cmak_user }}"
    create_home: no

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ cmak_user }}"
    group: "{{ cmak_user }}"
  loop:
    - "{{ cmak_install_path }}"
    - "{{ cmak_logging_path }}"

- name: Create temporary directory
  tempfile:
    state: directory
  register: temp_dir

- name: Download archive
  unarchive:
    src: "{{ cmak_dist_url }}/{{ cmak_version }}/cmak-{{ cmak_version }}.zip"
    dest: "{{ temp_dir.path }}/"
    remote_src: yes
    owner: "{{ cmak_user }}"
    group: "{{ cmak_user }}"
    creates: "{{ temp_dir.path }}/cmak-{{ cmak_version }}"

- name: Move files
  shell: "mv -f {{ temp_dir.path }}/cmak-{{ cmak_version }}/* {{ cmak_install_path }}/"
  args:
    creates: "{{ cmak_install_path }}/bin/cmak"

- name: Change permissions
  file:
    path: "{{ cmak_install_path }}"
    recurse: yes
    owner: "{{ cmak_user }}"
    group: "{{ cmak_user }}"

- name: Setup configuration
  template:
    src: "conf/{{ item }}"
    dest: "{{ cmak_install_path }}/conf/{{ item }}"
    owner: "{{ cmak_user }}"
    group: "{{ cmak_user }}"
    mode: 0600
  loop:
    - application.conf
    - environment
    - logback.xml

- name: Install service units
  template:
    src: systemd/cmak.service
    dest: /etc/systemd/system/cmak.service
    owner: root
    mode: 0644
