---
- name: Download archive
  unarchive:
    src: "{{ cruise_control_dist_url }}/{{ cruise_control_version }}.tar.gz"
    remote_src: yes
    dest: "{{ cruise_control_build_path }}"
  delegate_to: 127.0.0.1

- name: Init git repository
  command: git init
  args:
    chdir: "{{ cruise_control_build_path }}/cruise-control-{{ cruise_control_version }}"
  delegate_to: 127.0.0.1

- name: Build main distribution
  command: ./gradlew --console=plain jar
  args:
    chdir: "{{ cruise_control_build_path }}/cruise-control-{{ cruise_control_version }}"
  delegate_to: 127.0.0.1

- name: Build metrics distribution
  command: ./gradlew --console=plain jar copyDependantLibs
  args:
    chdir: "{{ cruise_control_build_path }}/cruise-control-{{ cruise_control_version }}"
  delegate_to: 127.0.0.1

- name: Remove source and compiled files
  file:
    state: absent
    path: "{{ cruise_control_build_path }}/cruise-control-{{ cruise_control_version }}/{{ item }}"
  loop:
    - build.gradle
    - buildSrc/
    - checkstyle/
    - cruise-control/src/
    - cruise-control/build/classes/
    - cruise-control/build/resources/
    - cruise-control/build/tmp/
    - cruise-control-core/src/
    - cruise-control-core/build/classes/
    - cruise-control-core/build/resources/
    - cruise-control-core/build/tmp/
    - cruise-control-metrics-reporter/src/
    - cruise-control-metrics-reporter/build/classes/
    - cruise-control-metrics-reporter/build/resources/
    - cruise-control-metrics-reporter/build/tmp/
    - docs/
    - gradle/
    - gradle.properties
    - gradlew
    - gradlew.bat
    - semantic-build-versioning.gradle
    - settings.gradle
  delegate_to: 127.0.0.1

- name: Package distribution
  archive:
    dest: "{{ cruise_control_archive_path }}"
    path: "{{ cruise_control_build_path }}/cruise-control-{{ cruise_control_version }}"
  delegate_to: 127.0.0.1
