---
- name: Create user
  user:
    name: "{{ zookeeper_user }}"
    create_home: no

- name: Copy sysctl config
  copy:
    src: sysctl.d/
    dest: /etc/sysctl.d/
    owner: root
    group: root
    mode: 0440

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ zookeeper_user }}"
  loop:
    - "{{ zookeeper_install_path }}"
    - "{{ zookeeper_logging_path }}"
    - "{{ zookeeper_data_path }}"
    - "{{ zookeeper_logs_path }}"

- name: Download archive
  unarchive:
    src: "{{ zookeeper_dist_url }}/zookeeper-{{ zookeeper_version }}/apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz"
    remote_src: yes
    dest: "{{ zookeeper_install_path }}"
    extra_opts:
      - --strip-components=1
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_user }}"
    creates: "{{ zookeeper_install_path }}/bin"

- name: Add binaries to PATH
  copy:
    dest: /etc/profile.d/zookeeper.sh
    content: "export PATH=${PATH}:{{ zookeeper_install_path }}/bin"
    owner: root
    mode: 0755

- name: Setup configuration
  template:
    src: "conf/{{ item }}"
    dest: "{{ zookeeper_install_path }}/conf/{{ item }}"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_user }}"
    mode: 0644
  loop:
    - zookeeper-env.sh
    - config.properties
    - log4j.properties

- name: Set Zookeeper ID
  copy:
    content: "{{ zookeeper_node_id }}"
    dest: "{{ zookeeper_data_path }}/myid"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_user }}"
    mode: 0644

- name: Adjust server script
  replace:
    path: "{{ zookeeper_install_path }}/bin/zkServer.sh"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop:
    - { regexp: "ZOO_LOG_FILE=.*\\.log", replace: "ZOO_LOG_FILE=server.log" }
    - { regexp: "_ZOO_DAEMON_OUT=.*\\.out\"", replace: "_ZOO_DAEMON_OUT=$ZOO_LOG_DIR/daemon.out" }

- name: Setup log rotate
  template:
    src: "logrotate/zookeeper"
    dest: "/etc/logrotate.d/zookeeper"
    owner: root
    mode: 0644

- name: Install service unit
  template:
    src: "systemd/zookeeper.service"
    dest: "/etc/systemd/system/zookeeper.service"
    owner: root
    mode: 0644
